plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jcs.read'
    compileSdk 34

    defaultConfig {
        applicationId "com.jcs.read"
        minSdk 19
        targetSdk 34
        versionCode 16
        versionName "0.3.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
